title: Rudy Dey # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am recent graduate from Universit of Georgia with a BBA in Economics and Applied Data Science Certificate.
  I will be starting the Master of Science in Business Analytics from Georgia Institure of Technology in Fall 2022
  <br><br>
  I am interested in learning more about the uses of the intersection between economics and data science in the areas of public policy and business.
  This site serves as an archive of my class projects as well as some of my personal projects.
  <br><br>
  <a href="https://www.linkedin.com/in/rudydey/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
